ALTER SESSION SET PLSCOPE_SETTINGS = 'IDENTIFIERS:NONE'; -- fix na ORA-0600


DROP sequence  "PHOTOGALLERY"."ALBUM_ID_SEQ";
DROP sequence  "PHOTOGALLERY"."PHOTO_ID_SEQ";
DROP TABLE "PHOTOGALLERY"."PHOTOS" ;
DROP TABLE "PHOTOGALLERY"."ALBUMS";
DROP table "PHOTOGALLERY"."USERS";



CREATE SEQUENCE  "PHOTOGALLERY"."ALBUM_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 200 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "PHOTOGALLERY"."PHOTO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


CREATE TABLE "PHOTOGALLERY"."USERS" 
   (	"EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"SURNAME" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY" ;
  
COMMENT ON TABLE "PHOTOGALLERY"."USERS" is 'U¿ytkownicy';
COMMENT ON COLUMN "PHOTOGALLERY"."USERS"."EMAIL" is 'Adres e-mail u¿ytkownika';
COMMENT ON COLUMN "PHOTOGALLERY"."USERS"."NAME" is 'Imiê';
COMMENT ON COLUMN "PHOTOGALLERY"."USERS"."SURNAME" is 'Nazwisko';
COMMENT ON COLUMN "PHOTOGALLERY"."USERS"."PASSWORD" is 'Has³o';
--albumy  
  
  CREATE TABLE "PHOTOGALLERY"."ALBUMS" 
   (	"ALBUM_ID" NUMBER NOT NULL ENABLE, 
	"USER_MAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"AUD_CREATE" DATE NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(800 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ALBUMS_PK" PRIMARY KEY ("ALBUM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY"  ENABLE, 
	 CONSTRAINT "ALBUMS_USERS_FK" FOREIGN KEY ("USER_MAIL")
	  REFERENCES "PHOTOGALLERY"."USERS" ("EMAIL") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY" ;
  
COMMENT ON TABLE "PHOTOGALLERY"."ALBUMS" is 'Albumy';
COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."ALBUM_ID" is 'Techniczny ID';
COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."USER_MAIL" is 'E-mail wlasciciela albumu (klucz obcy do USERS)';
COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."NAME" is 'Nazwa';
COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."AUD_CREATE" is 'Data utworzenia';
COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."DESCRIPTION" is 'Opis albumu';

  CREATE OR REPLACE TRIGGER "PHOTOGALLERY"."ALBUM_ID_TRIGGER" 
BEFORE INSERT ON ALBUMS 
REFERENCING OLD AS old NEW AS new 
FOR EACH ROW 
BEGIN
  IF :new.album_id is NULL THEN
    SELECT ALBUM_ID_SEQ.nextval INTO :new.album_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "PHOTOGALLERY"."ALBUM_ID_TRIGGER" ENABLE;

--fotki

CREATE TABLE "PHOTOGALLERY"."PHOTOS" 
   (	"PHOTO_ID" NUMBER NOT NULL ENABLE, 
	"ALBUM_ID" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"AUD_CREATE" DATE NOT NULL ENABLE, 
	"PLACE" VARCHAR2(200 BYTE), 
	 CONSTRAINT "PHOTOS_PK" PRIMARY KEY ("PHOTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY"  ENABLE, 
	 CONSTRAINT "PHOTOS_ALBUMS_ID" FOREIGN KEY ("ALBUM_ID")
	  REFERENCES "PHOTOGALLERY"."ALBUMS" ("ALBUM_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY" ;
  
COMMENT ON TABLE "PHOTOGALLERY"."PHOTOS" is 'Albumy';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."ALBUM_ID" is 'Techniczny ID';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."PHOTO_ID" is 'E-mail wlasciciela albumu (klucz obcy do USERS)';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."FILENAME" is 'Nazwa';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."AUD_CREATE" is 'Data utworzenia';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."DESCRIPTION" is 'Opis albumu';

  CREATE OR REPLACE TRIGGER "PHOTOGALLERY"."PHOTO_ID_TRIGGER" BEFORE INSERT ON PHOTOS 
REFERENCING OLD AS old NEW AS new 
FOR EACH ROW 
BEGIN
   IF :new.photo_id is NULL THEN
    SELECT PHOTO_ID_SEQ.nextval INTO :new.photo_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "PHOTOGALLERY"."PHOTO_ID_TRIGGER" ENABLE;







