ALTER SESSION SET PLSCOPE_SETTINGS = 'IDENTIFIERS:NONE'; -- fix na ORA-0600


DROP sequence  "PHOTOGALLERY"."ALBUM_ID_SEQ";
DROP sequence  "PHOTOGALLERY"."PHOTO_ID_SEQ";
DROP TABLE "PHOTOGALLERY"."PHOTOS" ;
DROP TABLE "PHOTOGALLERY"."ALBUMS";
DROP table "PHOTOGALLERY"."USERS";



CREATE SEQUENCE  "PHOTOGALLERY"."ALBUM_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 200 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "PHOTOGALLERY"."PHOTO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


CREATE TABLE "PHOTOGALLERY"."USERS" 
   (	"EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"SURNAME" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY" ;
  
COMMENT ON TABLE "PHOTOGALLERY"."USERS" is 'U�ytkownicy';
COMMENT ON COLUMN "PHOTOGALLERY"."USERS"."EMAIL" is 'Adres e-mail u�ytkownika';
COMMENT ON COLUMN "PHOTOGALLERY"."USERS"."NAME" is 'Imi�';
COMMENT ON COLUMN "PHOTOGALLERY"."USERS"."SURNAME" is 'Nazwisko';
COMMENT ON COLUMN "PHOTOGALLERY"."USERS"."PASSWORD" is 'Has�o';
--albumy  
  
  CREATE TABLE "PHOTOGALLERY"."ALBUMS" 
   (	"ALBUM_ID" NUMBER NOT NULL ENABLE, 
	"USER_MAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"AUD_CREATE" DATE NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(800 BYTE), 
	 CONSTRAINT "ALBUMS_PK" PRIMARY KEY ("ALBUM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY"  ENABLE, 
	 CONSTRAINT "USER_ALBUM_UNIQUE" UNIQUE ("USER_MAIL", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ALBUMS_USERS_FK" FOREIGN KEY ("USER_MAIL")
	  REFERENCES "PHOTOGALLERY"."USERS" ("EMAIL") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY" ;

   COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."ALBUM_ID" IS 'Techniczny ID';
   COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."USER_MAIL" IS 'E-mail wlasciciela albumu (klucz obcy do USERS)';
   COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."NAME" IS 'Nazwa';
   COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."AUD_CREATE" IS 'Data utworzenia';
   COMMENT ON COLUMN "PHOTOGALLERY"."ALBUMS"."DESCRIPTION" IS 'Opis albumu';
   COMMENT ON TABLE "PHOTOGALLERY"."ALBUMS"  IS 'Albumy';

  CREATE OR REPLACE TRIGGER "PHOTOGALLERY"."ALBUM_ID_TRIGGER" 
BEFORE INSERT ON ALBUMS 
REFERENCING OLD AS old NEW AS new 
FOR EACH ROW 
BEGIN
  IF :new.album_id is NULL THEN
    SELECT ALBUM_ID_SEQ.nextval INTO :new.album_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "PHOTOGALLERY"."ALBUM_ID_TRIGGER" ENABLE;

--fotki

CREATE TABLE "PHOTOGALLERY"."PHOTOS" 
   (	"PHOTO_ID" NUMBER NOT NULL ENABLE, 
	"ALBUM_ID" NUMBER NOT NULL ENABLE,
	 "TITLE" VARCHAR(250 BYTE) NOT NULL ENABLE,
	"FILENAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"AUD_CREATE" DATE NOT NULL ENABLE, 
	"PLACE" VARCHAR2(200 BYTE), 
	 CONSTRAINT "PHOTOS_PK" PRIMARY KEY ("PHOTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY"  ENABLE, 
	 CONSTRAINT "PHOTOS_ALBUMS_ID" FOREIGN KEY ("ALBUM_ID")
	  REFERENCES "PHOTOGALLERY"."ALBUMS" ("ALBUM_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PHOTOGALLERY" ;
  
COMMENT ON TABLE "PHOTOGALLERY"."PHOTOS" is 'Albumy';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."ALBUM_ID" is 'Techniczny ID';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."PHOTO_ID" is 'E-mail wlasciciela albumu (klucz obcy do USERS)';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."FILENAME" is 'Nazwa';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."AUD_CREATE" is 'Data utworzenia';
COMMENT ON COLUMN "PHOTOGALLERY"."PHOTOS"."DESCRIPTION" is 'Opis albumu';

  CREATE OR REPLACE TRIGGER "PHOTOGALLERY"."PHOTO_ID_TRIGGER" BEFORE INSERT ON PHOTOS 
REFERENCING OLD AS old NEW AS new 
FOR EACH ROW 
BEGIN
   IF :new.photo_id is NULL THEN
    SELECT PHOTO_ID_SEQ.nextval INTO :new.photo_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "PHOTOGALLERY"."PHOTO_ID_TRIGGER" ENABLE;

 CREATE TABLE "PHOTOGALLERY"."EVENT_TYPES" 
   (	"EVENT_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"EVENT_KEY" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EVENT_TYPES_PK" PRIMARY KEY ("EVENT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "EVENT_TYPES_UK1" UNIQUE ("EVENT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PHOTOGALLERY"."EVENT_TYPES"."EVENT_TYPE_ID" IS 'Klucz techniczny';
   COMMENT ON COLUMN "PHOTOGALLERY"."EVENT_TYPES"."EVENT_KEY" IS 'Klucz zdarzenia';
   COMMENT ON TABLE "PHOTOGALLERY"."EVENT_TYPES"  IS 'Tabela definiująca możliwe typy zdarzeń';

  CREATE OR REPLACE TRIGGER "PHOTOGALLERY"."EVENT_TYPES_TRG" BEFORE INSERT ON EVENT_TYPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.EVENT_TYPE_ID IS NULL THEN
      SELECT EVENT_TYPES_SEQ.NEXTVAL INTO :NEW.EVENT_TYPE_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PHOTOGALLERY"."EVENT_TYPES_TRG" ENABLE;



  CREATE TABLE "PHOTOGALLERY"."EVENTS" 
   (	"EVENT_ID" NUMBER NOT NULL ENABLE, 
	"EVENT_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"AUD_CREATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "EVENTS_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "EVENTS_EVENT_TYPES_FK1" FOREIGN KEY ("EVENT_TYPE_ID")
	  REFERENCES "PHOTOGALLERY"."EVENT_TYPES" ("EVENT_TYPE_ID") ENABLE, 
	 CONSTRAINT "EVENTS_USERS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "PHOTOGALLERY"."USERS" ("EMAIL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PHOTOGALLERY"."EVENTS"."EVENT_ID" IS 'Klucz techniczny';
   COMMENT ON COLUMN "PHOTOGALLERY"."EVENTS"."EVENT_TYPE_ID" IS 'Klucz obcy do tabeli z typami zdarzeń';
   COMMENT ON COLUMN "PHOTOGALLERY"."EVENTS"."USER_ID" IS 'Indetyfikator użytkownika [e-mail]';
   COMMENT ON COLUMN "PHOTOGALLERY"."EVENTS"."AUD_CREATE" IS 'Data zdarzenia';
   COMMENT ON TABLE "PHOTOGALLERY"."EVENTS"  IS 'Tabela przechowująca zdarzenia w systemie';

  CREATE INDEX "PHOTOGALLERY"."EVENTS_INDEX1" ON "PHOTOGALLERY"."EVENTS" ("EVENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE TRIGGER "PHOTOGALLERY"."EVENTS_TRG" BEFORE INSERT ON EVENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.EVENT_ID IS NULL THEN
      SELECT EVENTS_SEQ.NEXTVAL INTO :NEW.EVENT_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PHOTOGALLERY"."EVENTS_TRG" ENABLE;


Insert Into Event_Types(Event_Key) Values ('USER_CREATED')
Insert Into Event_Types(Event_Key) Values ('ALBUM_CREATED')
Insert Into Event_Types(Event_Key) Values ('PHOTO_ADDED')
Insert Into Event_Types(Event_Key) Values ('USER_LOGGED_IN')
Insert Into Event_Types(Event_Key) Values ('USER_LOGGED_OUT')

CREATE OR REPLACE TRIGGER USER_CREATED_EVENT 
After Insert On Users 
Referencing New As New 
FOR EACH ROW 
Begin
  Insert Into Events (Event_Type_Id, User_Id, Aud_Create) Values ((Select Event_Type_Id From Event_Types Where Event_Key = 'USER_CREATED'), :New.Email, Current_Date);
END;

CREATE OR REPLACE TRIGGER ALBUM_ADDED_EVENT 
AFTER INSERT ON ALBUMS 
FOR EACH ROW 
Begin
  Insert Into Events (Event_Type_Id, User_Id, Aud_Create) Values ((Select Event_Type_Id From Event_Types Where Event_Key = 'ALBUM_CREATED'), :New.User_Mail, Current_Date);
END;

CREATE OR REPLACE TRIGGER PHOTO_ADDED_EENT 
AFTER INSERT ON PHOTOS 
FOR EACH ROW 
Begin
  Insert Into Events (Event_Type_Id, User_Id, Aud_Create) Values ((Select Event_Type_Id From Event_Types Where Event_Key = 'PHOTO_ADDED'),
  (select Albums.User_Mail from albums where albums.album_id = :new.album_id ),
  Current_Date);
END;


